apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "nginx.fullname" . }}
spec:
  gateways:
    - istio-system/default
  hosts:
  - "nginx.playkids.io"
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ include "nginx.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: 80
